apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bx8a9eg4d-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bx8a9eg4d-go 
  name: bx8a9eg4d-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bx8a9eg4d-go 
