apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bx8a9eg4d-go 
  janus-idp.io/tekton: bx8a9eg4d-go
  backstage.io/kubernetes-id: bx8a9eg4d-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bx8a9eg4d-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml